NETWORK_PASSPHRASE=Public Global Stellar Network
HORIZON_URL=https://horizon.stellar.org
CURRENCY_CODE=LOTG49
ORG_NAME=LOT Pi Holding Universal
ORG_LOGO=https://lotpi.org/logo.png
ISSUER=GAOI54SELTEVNL6APGH7ZILQHASUQDYDM4NOCARUDYFAJ545Q3NOVRHR
HOME_DOMAIN=lotpi.org
