NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=["GAOI54SELTEVNL6APGH7ZILQHASUQDYDM4NOCARUDYFAJ545Q3NOVRHR"]

[[CURRENCIES]]
code="LOTG49"
issuer="GAOI54SELTEVNL6APGH7ZILQHASUQDYDM4NOCARUDYFAJ545Q3NOVRHR"
name="LOTG49 Gold Token"
desc="1 LOTG49 = สิทธิ์แลกเปลี่ยนทองคำ 1 กรัม จาก LOT Pi Holding Universal"
image="https://nopphakao7108-alt.github.io/lotpi-org/logo.png"