NETWORK_PASSPHRASE=Public Global Stellar Network ; v1
ACCEPTS_AUTH=true
ACCEPTS_DIRECT=true
CORS_ALLOWED_ORIGINS=https://*
HORIZON_URL=https://horizon.stellar.org
ORG_NAME=โรงกษาปณ์ชุมชน lotpi.org
ORG_LOGO=https://nopphaklao7108-alt.github.io/lotpi-org/logo.png
